### ISSUE TITLE
Examples don't seem to work on chrome

### ISSUE THREAD

**Issue by jmona789** [mir3z/aalib.js#1]
When I try to open the example html files on chrome I get this error: 
Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
Works on Safari though

**Comment by mir3z** [comment]
You mean all example files? Are you opening it directly from github by accessing http://mir3z.github.io/aalib.js/examples/lenna.html or cloning repo to your own machine?

**Comment by jmona789** [comment]
I cloned it

**Comment by mir3z** [comment]
In that case you have to set up http server and server examples from it.
