### ISSUE TITLE
Tainted by cross-origin data

### ISSUE THREAD

**Issue by ashlin4010** [mir3z/aalib.js#2]
```
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at Function.value (file:///E:/Downloads/mir3z-aalib.js-bf96691/build/aalib.js:255:136)
    at HTMLImageElement.i (file:///E:/Downloads/mir3z-aalib.js-bf96691/build/aalib.js:109:106)
```
I don't know how to fix this

**Comment by mir3z** [comment]
Most likely you are trying to load image/video which comes from a different origin than your script. Any browser doesn't allow you to do that. 

Just make sure everything is served from the same origin = from the same server. You may use https://www.npmjs.com/package/http-server to easily setup simple server for your scripts/assets/pages/whatever you need to.
