### ISSUE TITLE
Image download button for Playground

### ISSUE THREAD

**Issue by oleteacher** [mir3z/aalib.js#6]
Very nice work, thank you for sharing it.

Wishing to use in classroom as kids would love it.

Have been trying to create a download button so once art is created, kids can simply click the button to download image. Right clicking and saving image as is little confusing for younger kids.

Any pointers you could provide would be appreciated.

**Comment by mir3z** [comment]
Hello, you can save and download canvas as an image. Just take a look on [the link](http://weworkweplay.com/play/saving-html5-canvas-as-image/) or google for something like "save html5 canvas".

**Comment by oleteacher** [comment]
Thank you @mir3z for tip.

I had explored that option but was never successful. Will try some more:)
